name: Create Commit

run-name: ${{ inputs.uuId }}

on:
  workflow_dispatch:
    inputs:
      projectId:
        description: 'Project ID to fetch data for'
        required: true
        default: 'defaultProjectId'
      branch:
        description: 'Branch to fetch data and push changes to'
        required: true
        default: 'main'
      branchId:
        description: 'BranchId'
        required: true
        default: 'main'
      email:
        description: 'Email for git config'
        required: true
        default: 'your-username@users.noreply.github.com'
      userName:
        description: 'GitHub Username for commits'
        required: true
        default: 'GitHub Actions'
      commitMessage:
        description: 'Commit message'
        required: true
        default: 'Add YAML files for project ID'
      uuId:
        description: 'Unique Id'
        required: true
        default: '0000'

permissions:
  contents: write

jobs:
  create_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Extract Version
        run: |
          VERSION=$(cat version.yaml | awk -F'=' '{print $2}' | awk -F'.' '{print $1}')
          echo "Extracted major version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV


      - name: Install Node Package
        env:
          DIGIA_TOKEN: ${{ secrets.DIGIA_TOKEN }}
        run: |
          curl -o commit_changes.sh "https://digia-backend-files.s3.ap-south-1.amazonaws.com/github-scripts/version/$VERSION/commit_changes.sh"
          chmod +x commit_changes.sh
          ./commit_changes.sh "$projectId" "$branchId" "$branch" "$VERSION"


      - name: Cleanup Temporary Files
        run: |
          sudo chmod -R 777 node_modules package.json package-lock.json scripts/json_yaml.js
          sudo rm -rf node_modules package.json package-lock.json scripts/json_yaml.js

      - name: Commit and Push Changes
        env:
          BRANCH: ${{ github.event.inputs.branch }}
          USER_EMAIL: ${{ github.event.inputs.email }}
          USER_NAME: ${{ github.event.inputs.userName }}
          COMMIT_MESSAGE: ${{ github.event.inputs.commitMessage }}
          PROJECT_ID: ${{ github.event.inputs.projectId }}
          UUID: ${{ github.event.inputs.uuId }}
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
          git pull origin $BRANCH
          git add .
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "$COMMIT_MESSAGE"
            git push origin $BRANCH
          fi
