name: Fetch API Data and Convert to YAML

on:
  workflow_dispatch:
    inputs:
      projectId:
        description: 'Project ID to fetch data for'
        required: true
        default: 'defaultProjectId'

  push:
    branches:
      - main  # Trigger on push to the main branch

permissions:
  contents: write

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Initialize Node.js Project and Install Dependencies
        run: |
          npm init -y           # Automatically create package.json
          npm install axios js-yaml

      - name: Run Fetch and Convert Script
        run: |
          node scripts/json_yaml.js ${{ github.event.inputs.projectId }}

      # - name: Move YAML Files
      #   run: |
      #     mkdir -p datasources/rest
      #     mv *.yaml datasources/rest/
      #     echo "YAML files created in datasources/rest/"

      # - name: Cleanup Temporary Files
      #   run: |
      #     rm -rf node_modules package.json package-lock.json
