name: Fetch API Data and Convert to YAML

on:
  workflow_dispatch:
    inputs:
      projectId:
        description: 'Project ID to fetch data for'
        required: true
        default: 'defaultProjectId'
      branch:
        description: 'Branch to fetch data and push changes to'
        required: true
        default: 'main'
      branchId:
        description: 'BranchId'
        required: true
        default: 'main'
      email:
        description: 'Email for git config'
        required: true
        default: 'your-username@users.noreply.github.com'
      userName:
        description: 'GitHub Username for commits'
        required: true
        default: 'GitHub Actions'
      commitMessage:
        description: 'Commit message'
        required: true
        default: 'Add YAML files for project ID'

permissions:
  contents: write

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Initialize Node.js Project and Install Dependencies
        run: |
          npm init -y                   # Automatically create package.json
          npm install axios js-yaml     # Install required packages

      - name: Run Fetch and Convert Script
        env:
          DIGIA_TOKEN: ${{ secrets.DIGIA_TOKEN }}
        run: |
          node scripts/json_yaml.js ${{ github.event.inputs.projectId }} ${{ github.event.inputs.branchId }} ${{ github.event.inputs.branch }}

      - name: Commit and Push Changes
        env:
          BRANCH: ${{ github.event.inputs.branch }}
          USER_EMAIL: ${{ github.event.inputs.email }}
          USER_NAME: ${{ github.event.inputs.userName }}
          COMMIT_MESSAGE: ${{ github.event.inputs.commitMessage }}
          PROJECT_ID: ${{ github.event.inputs.projectId }}
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
          git pull origin $BRANCH
          git add .
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "$COMMIT_MESSAGE"
            git push origin $BRANCH
          fi

      - name: Cleanup Temporary Files
        run: |
          rm -rf node_modules package.json package-lock.json  # Cleanup after job
