name: Fetch API Data and Convert to YAML

on:
  workflow_dispatch:
    inputs:
      projectId:
        description: 'Project ID to fetch data for'
        required: true
        default: 'defaultProjectId'

  push:
    branches:
      - main  # Trigger on push to the main branch

permissions:
  contents: write

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Fetch API Data and Convert to YAML
        run: |
          # Use npx to run the script with required packages inline
          npx -y axios@latest js-yaml@latest node scripts/json_yaml.js ${{ github.event.inputs.projectId }}

      - name: Create YAML Files
        run: |
          # Move generated YAML files to the desired directory
          mv datasources/rest/*.yaml datasources/rest/
          echo "YAML files created in datasources/rest/"
