name: Merge Branches

on:
  workflow_dispatch:
    inputs:
      projectId:
        description: 'Project ID to fetch data for'
        required: true
        default: 'defaultProjectId'

  pull_request:
    types:
      - closed  # Runs when a PR is merged
          
permissions:
  contents: write

jobs:
  merge_branches:
    if: github.event.pull_request.merged == true  # Ensures it runs only on merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check for First Commit
        run: |
          FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
          echo "First commit hash: $FIRST_COMMIT"
          echo "Current commit hash: $GITHUB_SHA"
          if [[ "$FIRST_COMMIT" == "$GITHUB_SHA" ]]; then
            echo "Skipping workflow because this is the first commit."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Initialize Node.js Project and Install Dependencies
        run: |
          npm init -y                   # Automatically create package.json
          npm install axios js-yaml     # Install required packages

      - name: Get Branch Name
        run: echo "BASE_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
      
      - name: Fetch yaml_json.js Script
        run: |
          VERSION=$(cat version.yaml | awk -F'=' '{print $2}' | awk -F'.' '{print $1}')
          echo "Extracted major version: $VERSION"
          [ -d scripts ] || mkdir scripts
          curl -o scripts/yaml_json.js "https://digia-backend-files.s3.ap-south-1.amazonaws.com/github-scripts/version/$VERSION/yaml_json.js"
          chmod +x scripts/yaml_json.js

      - name: Run Fetch and Convert Script
        env:
           DIGIA_TOKEN: ${{ secrets.DIGIA_TOKEN }}
        run: |
          node scripts/yaml_json.js ${{ github.event.inputs.projectId }} $BASE_BRANCH

      - name: Cleanup Temporary Files
        run: |
          sudo chmod -R 777 node_modules package.json package-lock.json scripts/yaml_json.js
          sudo rm -rf node_modules package.json package-lock.json scripts/yaml_json.js

