name: Restore Commit


run-name: ${{ inputs.uuId }}

on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: "Commit hash to check out"
        required: true
      branchName:
        description: "Branch name (for reference only, not used for commit)"
        required: true
      projectId:
        description: "Project ID to fetch data for"
        required: true
      uuId:
        description: 'Unique Id'
        required: true
        default: '0000'

permissions:
  contents: write 

jobs:
  restore_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures full history is available

      - name: Checkout to Specific Commit
        run: |
          git checkout ${{ github.event.inputs.commitHash }}
          echo "Checked out to commit: ${{ github.event.inputs.commitHash }}"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Extract Version
        run: |
          VERSION=$(cat version.yaml | awk -F'=' '{print $2}' | awk -F'.' '{print $1}')
          echo "Extracted major version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV


      - name: Restore Commit
        env:
           DIGIA_TOKEN: ${{ secrets.DIGIA_TOKEN }}
           BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          curl -o merge_changes.sh "https://raw.githubusercontent.com/Digia-Technology-Private-Limited/digia_public_scripts/refs/heads/main/github/version/$VERSION/merge_changes.sh"
          chmod +x merge_changes.sh
          ./merge_changes.sh ${{ github.event.inputs.branchName }} "$VERSION"
